// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aghtwbqtuhllzzqqarlw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFnaHR3YnF0dWhsbHp6cXFhcmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2OTg3OTQsImV4cCI6MjA1OTI3NDc5NH0.wtx2q_bFW96Ymq_x_9Bhyk8W4YIbZvAHoNonIsGGmiA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);